import { Blocker, Deal } from '../types'

// ─── Seed Blockers ─────────────────────────────────────────────────────────────

export const SEED_BLOCKERS: Blocker[] = [
  {
    id: 'b1',
    title: 'SSO / SAML Integration',
    description:
      'Enterprise customers require Single Sign-On via SAML 2.0 or OIDC before security team sign-off. Blocks every Enterprise deal.',
    tags: ['security', 'enterprise', 'auth'],
    urgency: 'high',
    effort: 'medium',
    status: 'open',
    createdAt: '2024-01-10T09:00:00Z',
  },
  {
    id: 'b2',
    title: 'REST API & Webhooks',
    description:
      'Mid-market and enterprise customers want a documented REST API with webhook events to integrate with their existing tool stack.',
    tags: ['api', 'integration', 'developer'],
    urgency: 'high',
    effort: 'large',
    status: 'in_progress',
    createdAt: '2024-01-12T09:00:00Z',
  },
  {
    id: 'b3',
    title: 'Custom Reporting & Exports',
    description:
      'Customers need a custom dashboard builder, saved views, and the ability to export data as CSV or PDF for executive reports.',
    tags: ['reporting', 'analytics', 'export'],
    urgency: 'medium',
    effort: 'medium',
    status: 'open',
    createdAt: '2024-01-15T09:00:00Z',
  },
  {
    id: 'b4',
    title: 'Audit Logs & SOC 2',
    description:
      'Financial services and healthcare clients require detailed audit trails and SOC 2 Type II compliance documentation to pass procurement.',
    tags: ['compliance', 'security', 'enterprise'],
    urgency: 'high',
    effort: 'small',
    status: 'open',
    createdAt: '2024-01-18T09:00:00Z',
  },
  {
    id: 'b5',
    title: 'Mobile App (iOS / Android)',
    description:
      'Field sales teams and remote workers need a native mobile experience to manage their workflows on the go.',
    tags: ['mobile', 'ios', 'android'],
    urgency: 'low',
    effort: 'large',
    status: 'open',
    createdAt: '2024-01-20T09:00:00Z',
  },
]

// ─── Seed Deals ────────────────────────────────────────────────────────────────

export const SEED_DEALS: Deal[] = [
  {
    id: 'd1',
    companyName: 'Meridian Financial',
    contactName: 'Sarah Chen',
    dealValue: 85000,
    stage: 'negotiation',
    blockerIds: ['b1', 'b4'],
    notes: 'Security review pending. IT needs SSO and audit logs before sign-off. Strong champion in VP Engineering.',
    createdAt: '2024-01-08T09:00:00Z',
    updatedAt: '2024-02-10T09:00:00Z',
  },
  {
    id: 'd2',
    companyName: 'Apex Logistics',
    contactName: 'Marcus Webb',
    dealValue: 62000,
    stage: 'proposal',
    blockerIds: ['b1', 'b2'],
    notes: 'Needs SSO for 400+ user org and REST API to connect with their TMS. Pilot went well.',
    createdAt: '2024-01-14T09:00:00Z',
    updatedAt: '2024-02-12T09:00:00Z',
  },
  {
    id: 'd3',
    companyName: 'NovaTech Solutions',
    contactName: 'Priya Patel',
    dealValue: 48000,
    stage: 'demo',
    blockerIds: ['b2', 'b3'],
    notes: 'Developer-heavy team. Wants full API coverage before committing. Reporting is a big ask.',
    createdAt: '2024-01-20T09:00:00Z',
    updatedAt: '2024-02-14T09:00:00Z',
  },
  {
    id: 'd4',
    companyName: 'Crestwood Healthcare',
    contactName: 'Dr. James Okafor',
    dealValue: 110000,
    stage: 'negotiation',
    blockerIds: ['b1', 'b4'],
    notes: 'HIPAA requirements mean audit logs are non-negotiable. Legal team involved. Very high value.',
    createdAt: '2024-01-05T09:00:00Z',
    updatedAt: '2024-02-16T09:00:00Z',
  },
  {
    id: 'd5',
    companyName: 'Brightline Media',
    contactName: 'Tanya Russo',
    dealValue: 28000,
    stage: 'proposal',
    blockerIds: ['b3', 'b5'],
    notes: 'Marketing agency. Needs reports for client decks and mobile for their field content team.',
    createdAt: '2024-01-25T09:00:00Z',
    updatedAt: '2024-02-18T09:00:00Z',
  },
  {
    id: 'd6',
    companyName: 'Stratos Capital',
    contactName: 'Ryan Blackwood',
    dealValue: 75000,
    stage: 'proposal',
    blockerIds: ['b1', 'b4'],
    notes: 'VC-backed fintech. Risk & compliance team requires SOC 2 + SSO. Board has sign-off authority.',
    createdAt: '2024-01-18T09:00:00Z',
    updatedAt: '2024-02-20T09:00:00Z',
  },
  {
    id: 'd7',
    companyName: 'Veloce Commerce',
    contactName: 'Kenji Tanaka',
    dealValue: 41000,
    stage: 'discovery',
    blockerIds: ['b2'],
    notes: 'E-commerce platform. Purely API-driven evaluation. Wants webhooks for real-time inventory sync.',
    createdAt: '2024-02-01T09:00:00Z',
    updatedAt: '2024-02-22T09:00:00Z',
  },
  {
    id: 'd8',
    companyName: 'Ironclad Manufacturing',
    contactName: 'Dana Fischer',
    dealValue: 33000,
    stage: 'demo',
    blockerIds: ['b3', 'b5'],
    notes: 'Floor managers need mobile. Also wants weekly ops reports. Mid-size company, budget flexible.',
    createdAt: '2024-02-05T09:00:00Z',
    updatedAt: '2024-02-24T09:00:00Z',
  },
]
